$kind: http-request
description: |-
  Work with revenue and quantity schedules for opportunity products. Establish or reestablish a product schedule with multiple installments for an opportunity product. Delete all installments in a schedule.
  This resource is available in REST API version 43.0 and later.

  In API version 46.0 and later, established and re-established schedules support custom fields, validation rules, and Apex triggers. Deleting all schedules now also fires delete triggers.
  https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_opportunitylineitemschedules.htm
url: "{{_endpoint}}/services/data/v{{version}}/sobjects/OpportunityLineItem/:OPPORTUNITY_LINE_ITEM_ID/OpportunityLineItemSchedules"
method: GET
headers:
  Content-Type: application/json
pathVariables:
  OPPORTUNITY_LINE_ITEM_ID: ""
order: 17000
